export type TMissions = {
	id: number,
	title: string,
	description: string,
	profession: number,
	poste: number,
	min: number | null,
	max: number | null,
	profilSearch: string,
	dateStart: string,
	dateEnd: string,
	contrat: number,
	status: number,
	nbPatient: number,
	pourcentage: number,
	created_at: string,
	updated_at: string,
}